const colors = [
  {
    id: "49",
    nail_color: "Gleeful",
    color_type: "Purple",
    hex: "#805682 ",
    url: "https://www.revelnail.com/products/d90-gleeful?_pos=1&_sid=8ba5c79a3&_ss=r",
  },
  {
    id: "39",
    nail_color: "Phoebe",
    color_type: "Silver Glitter",
    hex: "#97939f ",
    url: "https://www.revelnail.com/products/d167-phoebe?_pos=1&_sid=df3269720&_ss=r",
  },
  {
    id: "31",
    nail_color: "Bette",
    color_type: "White",
    hex: "#FFF5F3",
    url: "https://www.revelnail.com/products/d8-bette?_pos=1&_sid=694a6ca46&_ss=r",
  },
  {
    id: "36",
    nail_color: "Gravel",
    color_type: "Gray",
    hex: "#050609 ",
    url: "https://foreverbeautypro.com/revel-nail-dip-powder-2oz-dp381-gravel-new-colors/",
  },
  {
    id: "46",
    nail_color: "Draco",
    color_type: "Mood Changing Purple Blue",
    hex: "#275384 ",
    url: "https://foreverbeautypro.com/revel-nail-mood-changing-2oz-dp225-draco/",
  },
  {
    id: "52",
    nail_color: "BF Freebie 2020",
    color_type: "Purple",
  },
  {
    id: "2",
    nail_color: "Hush",
    color_type: "Neutral",
    hex: "#a16162",
    url: "https://www.revelnail.com/products/d235-hush?_pos=1&_sid=9cc030601&_ss=r",
  },
  {
    id: "58",
    nail_color: "No label",
    color_type: "Purple",
  },
  {
    id: "26",
    nail_color: "Eleanor",
    color_type: "Red",
    hex: "#c12032 ",
    url: "https://foreverbeautypro.com/revel-nail-dipping-powder-dp16-eleanor-2oz/",
  },
  {
    id: "42",
    nail_color: "Pomegranate",
    color_type: "Rose Gold Glitter",
    hex: "#9c585d ",
    url: "https://www.revelnail.com/blogs/revel-nail-blog/fall-drop-in-collection-revel-nail-dip-powder",
  },
  {
    id: "8",
    nail_color: "Theia",
    color_type: "Gold glitter",
    hex: "#b29879 ",
    url: "https://www.revelnail.com/products/d170-theia?_pos=1&_sid=06b8554b0&_ss=r",
  },
  {
    id: "51",
    nail_color: "Elderberry",
    color_type: "Berry",
    hex: "#3f0025 ",
    url: "https://www.revelnail.com/products/d547-elderberry?_pos=1&_sid=cce94d2ca&_ss=r",
  },
  {
    id: "10",
    nail_color: "Spree",
    color_type: "Pink",
    hex: "#d82d39 ",
    url: "https://www.revelnail.com/products/revel-mates-duo-dip-polish-d244-spree?_pos=2&_sid=dc4649e0f&_ss=r",
  },
  {
    id: "50",
    nail_color: "Starburst",
    color_type: "Mood Changing Purple",
    hex: "#b2b1c2 ",
    url: "https://www.revelnail.com/products/dp202-starburst?_pos=1&_sid=243b9f30d&_ss=r",
  },
  {
    id: "32",
    nail_color: "Vivien",
    color_type: "Clear",
    hex: "#fdf4f3 ",
    url: "https://www.revelnail.com/products/d75-vivien-clear?_pos=1&_sid=b8a61dd3f&_ss=r",
  },
  {
    id: "57",
    nail_color: "Clara",
    color_type: "Blue",
    hex: "#63AA8A",
    url: "https://www.beyondpolish.com/products/revel-nail-dip-powder-clara-2-oz-d12",
  },
  {
    id: "22",
    nail_color: "Bubbly",
    color_type: "Sparkle Pink",
    hex: "#F8CFD5",
    url: "https://www.revelnail.com/products/d77-bubbly?_pos=1&_sid=628b1f1f4&_ss=r",
  },
  {
    id: "37",
    nail_color: "Coco",
    color_type: "Brown",
    hex: "#5D413D",
    url: "https://www.revelnail.com/products/d336-coco?_pos=1&_sid=357f211d3&_ss=r",
  },
  {
    id: "53",
    nail_color: "Dunk Tank",
    color_type: "Blue",
    hex: "#bfd7cb ",
    url: "https://i.pinimg.com/originals/35/3e/7f/353e7fc74023d4926e0ce0e46db5fda6.jpg",
  },
  {
    id: "47",
    nail_color: "Thief",
    color_type: "Purple",
    hex: "#251c2b ",
    url: "https://www.revelnail.com/products/d370-thief?_pos=1&_sid=d270401eb&_ss=r",
  },
  {
    id: "33",
    nail_color: "Keen",
    color_type: "Silver Gray",
    hex: "#505050 ",
    url: "https://foreverbeautypro.com/revel-nail-dipping-powder-dp94-keen-2oz/",
  },
  {
    id: "45",
    nail_color: "Truth",
    color_type: "Pink Purple",
    hex: "#843649 ",
    url: "https://www.revelnail.com/products/d340-truth?_pos=1&_sid=c5a180bc4&_ss=r",
  },
  {
    id: "3",
    nail_color: "Maurea",
    color_type: "Neutral",
    hex: "#c08d85 ",
    url: "https://www.amazon.com/-/es/Revel-Nail-Goddess-Sea-Maurea/dp/B07R8NGXHC",
  },
  {
    id: "41",
    nail_color: "Black Friday Freebie",
    color_type: "Blue",
  },
  {
    id: "55",
    nail_color: "No Label Freebie",
    color_type: "Green",
  },
  {
    id: "43",
    nail_color: "Key",
    color_type: "Purple",
    hex: "#532c39 ",
    url: "https://max4beauty.com/revel-nail-dip-powder-2-oz-d149-key/",
  },
  {
    id: "14",
    nail_color: "Bobbing for Apples",
    color_type: "Pink",
    hex: "#df3e81 ",
    url: "https://www.lacquertracker.com/polish/Revel/Bobbing_for_Apples",
  },
  {
    id: "4",
    nail_color: "Intrigued",
    color_type: "Purple",
    hex: "#551a33 ",
    url: "https://www.revelnail.com/products/d356-intrigued?_pos=1&_sid=ce11f05d2&_ss=r",
  },
  {
    id: "56",
    nail_color: "Wonder",
    color_type: "Yellow",
    hex: "#f5d855 ",
    url: "https://max4beauty.com/revel-nail-dip-powder-2-oz-d106-wonder/",
  },
  {
    id: "44",
    nail_color: "Cabernet",
    color_type: "Wine",
    hex: "#700C32",
    url: "https://www.revelnail.com/products/d338-cabernet?_pos=1&_sid=1ffeac695&_ss=r",
  },
  {
    id: "27",
    nail_color: "Lilian",
    color_type: "Red",
    hex: "#d50624 ",
    url: "https://foreverbeautypro.com/revel-nail-dip-powder-1oz-dp43-lilian/",
  },
  {
    id: "35",
    nail_color: "Carousel",
    color_type: "Multicolor Glitter",
    hex: "#6F5852",
    url: "https://www.revelnail.com/products/d606-carousel?_pos=1&_sid=e8665752c&_ss=r",
  },
  {
    id: "30",
    nail_color: "Virgin Islands",
    color_type: "Sun Changing Pink Neutral",
    hex: "#bf8aa5 ",
    url: "https://foreverbeautypro.com/revel-nail-sun-collection-2oz-sc10-virgin-islands/",
  },
  {
    id: "54",
    nail_color: "Curious",
    color_type: "Green",
    hex: "#466a51 ",
    url: "https://foreverbeautypro.com/revel-nail-dipping-powder-dp78-curious-2oz/",
  },
  {
    id: "13",
    nail_color: "Aloha",
    color_type: "Pink",
    hex: "#FEBEB4",
    url: "https://www.revelnail.com/products/aloha?_pos=1&_sid=a37d50afe&_ss=r",
  },
  {
    id: "20",
    nail_color: "Ava",
    color_type: "Light Pink",
    hex: "#f395a5 ",
    url: "https://foreverbeautypro.com/revel-nail-dipping-powder-dp6-ava-2oz/",
  },
  {
    id: "21",
    nail_color: "Ballet",
    color_type: "Light Pink",
    hex: "#FFD1D4",
    url: "https://www.revelnail.com/products/d315-ballet?_pos=1&_sid=e0b38ef65&_ss=r",
  },
  {
    id: "38",
    nail_color: "Arcade",
    color_type: "Glitter",
    hex: "#d33e06 ",
    url: "https://www.reddit.com/r/DipPowderNails/comments/hx5kax/revel_nail_wall_flower_arcade_limited_editions/",
  },
  {
    id: "19",
    nail_color: "Mystery Color",
    color_type: "Pink",
  },
  {
    id: "17",
    nail_color: "Idol",
    color_type: "Pink",
    hex: "#910947 ",
    url: "https://www.revelnail.com/products/revel-mates-duo-dip-polish-d255-idol?_pos=2&_sid=f82ef304d&_ss=r",
  },
  {
    id: "6",
    nail_color: "Royal",
    color_type: "Peachy Pink",
    hex: "#ff9290 ",
    url: "https://www.revelnail.com/products/d313-royal?_pos=1&_sid=76446e4d3&_ss=r",
  },
  {
    id: "16",
    nail_color: "Bloom",
    color_type: "Pink",
    hex: "#D3005F",
    url: "https://www.revelnail.com/products/d373-bloom?_pos=1&_sid=bcaea88ae&_ss=r",
  },
  {
    id: "12",
    nail_color: "Alley Oop",
    color_type: "Orange",
    hex: "#ec7a47 ",
    url: "https://poshmark.com/listing/Revel-Nail-Dip-Powder-5fa604f509d76050024d19f6",
  },
  {
    id: "18",
    nail_color: "Aurora",
    color_type: "Pale Pink",
    hex: "#FDCCBD ",
    url: "https://www.revelnail.com/products/d171-aurora?_pos=1&_sid=4cd119d5d&_ss=r",
  },
  {
    id: "15",
    nail_color: "Sculptor",
    color_type: "Mood Changing Pink",
    hex: "#ba00a7 ",
    url: "https://www.revelnail.com/products/dp220-sculptor?_pos=1&_sid=5c5a6ab77&_ss=r",
  },
  {
    id: "29",
    nail_color: "Eager",
    color_type: "Dark Red",
    hex: "#78182b ",
    url: "https://www.revelnail.com/products/d350-eager?_pos=1&_sid=111a6c4ba&_ss=r",
  },
  {
    id: "11",
    nail_color: "Parisian Romance",
    color_type: "Pink",
    hex: "#d3a584 ",
    url: "https://www.revelnaileu.com/products/parisian-romance-themed-set",
  },
  {
    id: "25",
    nail_color: "Playa Del Carmen",
    color_type: "Sun Changing Pink",
    hex: "#e0007a ",
    url: "https://foreverbeautypro.com/revel-nail-sun-collection-2oz-sc3-playa-del-carmen/\\",
  },
  {
    id: "23",
    nail_color: "Cyber Monday Freebie",
    color_type: "Pale Pink",
  },
  {
    id: "1",
    nail_color: "Pine",
    color_type: "Green",
    hex: "#002e1e",
    url: "https://www.revelnail.com/products/d339-pine?_pos=1&_sid=9dd7d8dd4&_ss=r",
  },
  {
    id: "34",
    nail_color: "Haute",
    color_type: "Neutral",
    hex: "#d8a59d ",
    url: "https://www.revelnail.com/products/d232-haute?_pos=1&_sid=36b94a248&_ss=r",
  },
  {
    id: "5",
    nail_color: "Whirlpool",
    color_type: "Blue",
    hex: "#acd1f0 ",
    url: "https://www.revelnail.com/products/dp203-whirlpool?_pos=1&_sid=c4545ca78&_ss=r",
  },
  {
    id: "28",
    nail_color: "Festival",
    color_type: "Red",
    hex: "#ae0002 ",
    url: "https://www.revelnail.com/products/d246-festival?_pos=1&_sid=7eb69f74b&_ss=r",
  },
  {
    id: "40",
    nail_color: "Mystery Box Freebie",
    color_type: "Silver",
  },
  {
    id: "48",
    nail_color: "Freebie",
    color_type: "Purple Orange Glitter",
  },
  {
    id: "24",
    nail_color: "Covetous",
    color_type: "Pale Pink",
    hex: "#FFC7D4",
    url: "https://www.revelnail.com/products/d129-covetous?_pos=1&_sid=4ff276e81&_ss=r",
  },
  {
    id: "7",
    nail_color: "Wicked",
    color_type: "Green",
    hex: "#2f321a ",
    url: "https://www.revelnail.com/products/wicked?_pos=1&_sid=4deddf9ce&_ss=r",
  },
  {
    id: "9",
    nail_color: "Shady",
    color_type: "Gray",
    hex: "#967a71 ",
    url: "https://www.revelnail.com/products/d230-shady?_pos=1&_sid=e1dfbd5db&_ss=r",
  },
];
