import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/NavBar";
import NailCard from "../components/NailCard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pick Your Polish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NailCard heading='Find your color'/>
    </div>
  );
}
